version: '3.2'

services:
  coordinator:
    image: "pl.battleships/vue-coordinator"    
    container_name: battleships-coordinator
    depends_on:
      - player1
      - player2
      - player3
      - player4
    build: coordinator/vueCoordinator
    ports:
      - 8080:80

  player1:
    image: pl.battleships/java-spring-ship
    build: javaSpringShip/
    container_name: battleships-player1
    ports:
      - 8051:8050
    environment:
      SERVER_PORT: 8050
      GAME_OPPONENTURL: http://player2:8050
      GAME_SLEEP: 200
     
  player2:
    image: pl.battleships/kotlin-spring-ship
    build: kotlinSpringShip/
    container_name: battleships-player2
    ports:
      - 8052:8050
    environment:
      SERVER_PORT: 8050
      GAME_OPPONENTURL: http://player1:8050
      GAME_SLEEP: 200

  player3:
    image: pl.battleships/java-quarkus-ship
    build: 
      context: javaQuarkusShip
      dockerfile: Dockerfile.native
    container_name: battleships-player3
    ports:
      - 8053:8050
    environment:
      QUARKUS_HTTP_PORT: 8050
      QUARKUS_REST_CLIENT_GAME_URL: http://player4:8050
      GAME_SLEEP: 200

  player4:
    image: pl.battleships/kotlin-quarkus-ship
    build: 
      context: kotlinQuarkusShip
      dockerfile: Dockerfile.native
    container_name: battleships-player4
    ports:
      - 8054:8050
    environment:
      QUARKUS_HTTP_PORT: 8050
      QUARKUS_REST_CLIENT_GAME_URL: http://player3:8050
      GAME_SLEEP: 200
