server:
  port: 8050

management:
  server: 0.0.0.0
  port: 8150
  ssl:
    enabled: false
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      cache:
        time-to-live: 30s

game:
  team: "none"
  opponentUrl: "localhost:8080"
  timeout: 1000
  sleep: 1500
